const fs = require('fs');
const path = require('path');

// Configuration
const WORKS_DIR = path.join(__dirname, '../assets/images/works');
const OUTPUT_FILE = path.join(__dirname, '../assets/js/gallery-data.js');

// Helper to get all files recursively
const getImages = (dir, category = '') => {
    let results = [];
    const list = fs.readdirSync(dir);

    list.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);

        if (stat && stat.isDirectory()) {
            // Recursively scan subdirectories
            // If we are in the root 'works' folder, the subdir is the category (e.g., STREET, Concerts)
            // If we are already deep (e.g. Concerts/Warfaze), preserve that structure or flatten?
            // Decision: We will use the top-level folder under 'works' as the main category filter.
            // Sub-folders will just be part of the path.

            const newCategory = category || file;
            results = results.concat(getImages(filePath, newCategory));
        } else {
            // Filter for image files
            if (/\.(jpg|jpeg|png|gif|webp)$/i.test(file)) {
                // Create the web-accessible path
                // We need the relative path from the 'works' folder
                // filePath included absolute path. 
                // We want: category/SubFolder/filename.jpg

                const relativePath = path.relative(WORKS_DIR, filePath).replace(/\\/g, '/');
                const pathParts = relativePath.split('/');

                // Top level folder is the Category
                const mainCategory = pathParts[0];

                // Generate a title from the filename (stub)
                const title = path.basename(file, path.extname(file)).replace(/[_-]/g, ' ');

                results.push({
                    src: `../assets/images/works/${encodeURI(relativePath)}`,
                    category: mainCategory.toLowerCase(), // Normalize for filtering
                    title: title,
                    originalCategory: mainCategory // Keep original casing for display if needed
                });
            }
        }
    });
    return results;
};

try {
    console.log('Scanning images...');
    const images = getImages(WORKS_DIR);

    const fileContent = `// Auto-generated by update-gallery.bat
const galleryData = ${JSON.stringify(images, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Success! Found ${images.length} images.`);
    console.log(`Data saved to: ${OUTPUT_FILE}`);
} catch (err) {
    console.error('Error generating gallery data:', err);
}
