const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const WORKS_DIR = path.join(__dirname, '../assets/images/works');
const OUTPUT_FILE = path.join(__dirname, '../assets/js/gallery-data.js');
const DIMENSIONS_FILE = path.join(__dirname, '../assets/js/image-dimensions.json');

// Try to load image dimensions (generated by generate_thumbnails.py)
let imageDimensions = {};
try {
    if (fs.existsSync(DIMENSIONS_FILE)) {
        imageDimensions = JSON.parse(fs.readFileSync(DIMENSIONS_FILE, 'utf-8'));
        console.log(`Loaded dimensions for ${Object.keys(imageDimensions).length} images`);
    }
} catch (e) {
    console.warn('Could not load image dimensions:', e.message);
}

// Helper to get dimensions for an image
const getDimensions = (relativePath) => {
    // Try to find in dimensions cache
    const normalizedPath = relativePath.replace(/\\/g, '/');

    // Try with 'works/' prefix
    let dims = imageDimensions[`works/${normalizedPath}`] || imageDimensions[normalizedPath];

    if (dims) {
        return { width: dims.width, height: dims.height };
    }

    return { width: 0, height: 0 };
};

// Helper to check if thumbnail exists
const getThumbPath = (relativePath) => {
    const parts = relativePath.split('/');
    const filename = parts.pop();
    parts.push('thumbs', filename);
    const thumbRelPath = parts.join('/');

    const thumbFullPath = path.join(WORKS_DIR, thumbRelPath);

    if (fs.existsSync(thumbFullPath)) {
        return `../assets/images/works/${encodeURI(thumbRelPath)}`;
    }
    return null;
};

// Helper to get all files recursively
const getImages = (dir, category = '') => {
    let results = [];
    const list = fs.readdirSync(dir);

    list.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);

        if (stat && stat.isDirectory()) {
            // Skip thumbs directories
            if (file === 'thumbs') return;

            // Recursively scan subdirectories
            const newCategory = category || file;
            results = results.concat(getImages(filePath, newCategory));
        } else {
            // Filter for image files (skip thumbs folder implicitly)
            if (/\.(webp|jpg|jpeg|png|gif)$/i.test(file)) {
                const relativePath = path.relative(WORKS_DIR, filePath).replace(/\\/g, '/');
                const pathParts = relativePath.split('/');

                // Top level folder is the Category
                const mainCategory = pathParts[0];

                // Generate a title from the filename
                const title = path.basename(file, path.extname(file)).replace(/[_-]/g, ' ');

                // Get thumbnail and dimensions
                const thumb = getThumbPath(relativePath);
                const dims = getDimensions(relativePath);

                const imageData = {
                    src: `../assets/images/works/${encodeURI(relativePath)}`,
                    category: mainCategory.toLowerCase(),
                    title: title,
                    originalCategory: mainCategory
                };

                // Add optional fields only if they exist
                if (thumb) {
                    imageData.thumb = thumb;
                }
                if (dims.width > 0) {
                    imageData.width = dims.width;
                    imageData.height = dims.height;
                }

                results.push(imageData);
            }
        }
    });
    return results;
};

try {
    console.log('Scanning images...');
    const images = getImages(WORKS_DIR);

    // Count images with thumbnails
    const withThumbs = images.filter(i => i.thumb).length;
    const withDims = images.filter(i => i.width > 0).length;

    const fileContent = `// Auto-generated by update-gallery.bat
// Progressive loading enabled: ${withThumbs} thumbnails, ${withDims} with dimensions
const galleryData = ${JSON.stringify(images, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Success! Found ${images.length} images.`);
    console.log(`  - With thumbnails: ${withThumbs}`);
    console.log(`  - With dimensions: ${withDims}`);
    console.log(`Data saved to: ${OUTPUT_FILE}`);
} catch (err) {
    console.error('Error generating gallery data:', err);
}
